# Generated by Django 3.1 on 2020-08-22 02:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('post_title', models.CharField(max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='A brief summary of the article for the post listing.', max_length=300)),
                ('main_content', wagtail.core.fields.StreamField([('blockquote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(help_text='Quote to be display on the page.', required=True)), ('attribution', wagtail.core.blocks.CharBlock(help_text='Attribution', max_length=100))])), ('Richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h1', 'h2', 'h3', 'ol', 'ul', 'link'], template='streams/simple_richtext_block.html')), ('ImageAndText', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='A full width image with a title.')), ('title', wagtail.core.blocks.CharBlock(max_length=60))])), ('Image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='A full width image.'))]))], blank=True, null=True)),
                ('internal_page_link', models.ForeignKey(blank=True, help_text='Select and internal page to link too.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('preview_image', models.ForeignKey(help_text='The preview image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
