# Generated by Django 3.1 on 2020-08-22 02:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_content',
            field=wagtail.core.fields.StreamField([('blockquote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(help_text='Quote to be display on the page.', required=True)), ('attribution', wagtail.core.blocks.CharBlock(help_text='Attribution', max_length=100))])), ('Richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'h1', 'h2', 'h3', 'ol', 'ul', 'link'], template='streams/simple_richtext_block.html')), ('ImageAndText', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image.')), ('title', wagtail.core.blocks.CharBlock(max_length=100))])), ('Image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image.'))]))], blank=True, null=True),
        ),
    ]
