# Generated by Django 3.1 on 2020-08-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200822_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_bottom_cta',
            field=models.CharField(help_text='CTA button text.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_bottom_subtitle',
            field=models.CharField(help_text='Bottom banner subtitle.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_bottom_title',
            field=models.CharField(help_text='Bottom banner title.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_design_body',
            field=models.TextField(help_text='Logo Design card body text.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='media_man_body',
            field=models.TextField(help_text='Media management card body text.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promise_subtitle',
            field=models.CharField(help_text='Our promise subtitle.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_body',
            field=models.TextField(help_text='SEO card body text.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='web_design_body',
            field=models.TextField(help_text='Web design card body text.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='web_dev_body',
            field=models.TextField(help_text='Web dev card body text.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='web_hosting_body',
            field=models.TextField(help_text='Web hosting card body text.', max_length=400, null=True),
        ),
    ]
